namespace:
  create: true
  name: database

replicaCount: 1

image:
  repository: mysql
  tag: "8.4"
  pullPolicy: IfNotPresent

auth:
  rootPassword: rootpass123
  database: appdb
  username: appuser
  password: apppass123

service:
  port: 3306

storage:
  existingClaim: mysql-pvc
  className: manual
  size: 2Gi
  accessMode: ReadWriteOnce
  persistentVolume:
    enabled: true
    name: mysql-pv
    hostPath: /data/mysql
    reclaimPolicy: Retain
  persistentVolumeClaim:
    enabled: true
    name: mysql-pvc

mysqlConfig: |
  [mysqld]
  character-set-server=utf8mb4
  collation-server=utf8mb4_unicode_ci

readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 5

resources: {}
