apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fake-gk
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NTHung2499/k8s-gitops-demo.git
    targetRevision: main
    path: charts/fake-gk
    helm:
      releaseName: fake-gk
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fake-gk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
