{{- if .Values.storage.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.persistentVolume.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.storage.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.storage.persistentVolume.reclaimPolicy }}
  storageClassName: {{ .Values.storage.className }}
  hostPath:
    path: {{ .Values.storage.persistentVolume.hostPath }}
    type: DirectoryOrCreate
{{- end }}
