namespace:
  create: true
  name: demo-helm

replicaCount: 1

image:
  repository: nginx
  tag: "1.27"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  host: ""
  path: /
  pathType: Prefix

resources: {}